name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches:
      - main
      - test
  pull_request:
    branches:
      - main

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Set up node
        uses: actions/checkout@v2
        with:
          node-version: '18'

      - name: Install dependencies, lint, and test
        run: npm install && npm run lint && npm run test
