name: Workflow

on: [pull_request]

jobs:
    Explore-Github-Actions:
        runs-on: ubuntu-latest

        steps:
            - name: prueba
              uses: actions/checkout@v4
            - run: npm install
            - run: yarn check-types
            - run: yarn lint
            - run: yarn test

